load("//:junit5.bzl", "java_junit5_test")

java_junit5_test(
    name = "ArrayTest",
    size = "small",
    srcs = ["ArrayTest.java"],
    test_package = "com.augustbonds.foundation",
    deps = [
        "//foundation/src/main/java/com/augustbonds/foundation",
    ]
)

java_junit5_test(
    name = "DictionaryTest",
    size = "small",
    srcs = ["DictionaryTest.java"],
    test_package = "com.augustbonds.foundation",
    deps = [
        "//foundation/src/main/java/com/augustbonds/foundation",
    ]
)

java_junit5_test(
    name = "SetTest",
    size = "small",
    srcs = ["SetTest.java"],
    test_package = "com.augustbonds.foundation",
    deps = [
        "//foundation/src/main/java/com/augustbonds/foundation",
    ]
)

java_junit5_test(
    name = "ListIteratorTest",
    size = "small",
    srcs = ["ListIteratorTest.java"],
    test_package = "com.augustbonds.foundation",
    deps = [
        "//foundation/src/main/java/com/augustbonds/foundation",
    ]
)

java_junit5_test(
    name = "FileTest",
    size = "small",
    srcs = ["FileTest.java"],
    test_package = "com.augustbonds.foundation",
    data = ["//foundation/src/test/resources:resources"],
    deps = [
        "//foundation/src/main/java/com/augustbonds/foundation",
    ]
)
